# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e4f12416d51deb35b402a6f14e61bc38"
name = "kea-promo-v2"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions,write_discounts,read_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
