api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "kea-product-discount"
type = "function"
uid = "b3d5b409-2ccb-d51a-05e1-0efa9686e63c9d9876ae"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
